default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lost_pet_finder_development

test:
  <<: *default
  database: lost_pet_finder_test

production:
  <<: *default
  database: lost_pet_finder_production
  username: lost_pet_finder
  password: <%= ENV['LOST_PET_FINDER_DATABASE_PASSWORD'] %>
